# Generated by Django 5.0.3 on 2024-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Salary', models.IntegerField(max_length=50)),
                ('native', models.CharField(max_length=50)),
            ],
        ),
    ]
